/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OngoingProjectsImport } from './routes/ongoing-projects'
import { Route as GetStartedImport } from './routes/get-started'
import { Route as DrawingCanvasImport } from './routes/drawing-canvas'
import { Route as AuctionPageImport } from './routes/auction-page'
import { Route as IndexImport } from './routes/index'
import { Route as AuthSignUpImport } from './routes/auth/sign-up'
import { Route as AuthSignInImport } from './routes/auth/sign-in'

// Create/Update Routes

const OngoingProjectsRoute = OngoingProjectsImport.update({
  id: '/ongoing-projects',
  path: '/ongoing-projects',
  getParentRoute: () => rootRoute,
} as any)

const GetStartedRoute = GetStartedImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRoute,
} as any)

const DrawingCanvasRoute = DrawingCanvasImport.update({
  id: '/drawing-canvas',
  path: '/drawing-canvas',
  getParentRoute: () => rootRoute,
} as any)

const AuctionPageRoute = AuctionPageImport.update({
  id: '/auction-page',
  path: '/auction-page',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auction-page': {
      id: '/auction-page'
      path: '/auction-page'
      fullPath: '/auction-page'
      preLoaderRoute: typeof AuctionPageImport
      parentRoute: typeof rootRoute
    }
    '/drawing-canvas': {
      id: '/drawing-canvas'
      path: '/drawing-canvas'
      fullPath: '/drawing-canvas'
      preLoaderRoute: typeof DrawingCanvasImport
      parentRoute: typeof rootRoute
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedImport
      parentRoute: typeof rootRoute
    }
    '/ongoing-projects': {
      id: '/ongoing-projects'
      path: '/ongoing-projects'
      fullPath: '/ongoing-projects'
      preLoaderRoute: typeof OngoingProjectsImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auction-page': typeof AuctionPageRoute
  '/drawing-canvas': typeof DrawingCanvasRoute
  '/get-started': typeof GetStartedRoute
  '/ongoing-projects': typeof OngoingProjectsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auction-page': typeof AuctionPageRoute
  '/drawing-canvas': typeof DrawingCanvasRoute
  '/get-started': typeof GetStartedRoute
  '/ongoing-projects': typeof OngoingProjectsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auction-page': typeof AuctionPageRoute
  '/drawing-canvas': typeof DrawingCanvasRoute
  '/get-started': typeof GetStartedRoute
  '/ongoing-projects': typeof OngoingProjectsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auction-page'
    | '/drawing-canvas'
    | '/get-started'
    | '/ongoing-projects'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auction-page'
    | '/drawing-canvas'
    | '/get-started'
    | '/ongoing-projects'
    | '/auth/sign-in'
    | '/auth/sign-up'
  id:
    | '__root__'
    | '/'
    | '/auction-page'
    | '/drawing-canvas'
    | '/get-started'
    | '/ongoing-projects'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuctionPageRoute: typeof AuctionPageRoute
  DrawingCanvasRoute: typeof DrawingCanvasRoute
  GetStartedRoute: typeof GetStartedRoute
  OngoingProjectsRoute: typeof OngoingProjectsRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuctionPageRoute: AuctionPageRoute,
  DrawingCanvasRoute: DrawingCanvasRoute,
  GetStartedRoute: GetStartedRoute,
  OngoingProjectsRoute: OngoingProjectsRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auction-page",
        "/drawing-canvas",
        "/get-started",
        "/ongoing-projects",
        "/auth/sign-in",
        "/auth/sign-up"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auction-page": {
      "filePath": "auction-page.tsx"
    },
    "/drawing-canvas": {
      "filePath": "drawing-canvas.jsx"
    },
    "/get-started": {
      "filePath": "get-started.tsx"
    },
    "/ongoing-projects": {
      "filePath": "ongoing-projects.tsx"
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
